CREATE TABLE IF NOT EXISTS app_user (
    email VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    profile VARCHAR(80) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    reset_token VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
