CREATE SEQUENCE IF NOT EXISTS APPLICATION_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS APPLICATION (
    id INTEGER PRIMARY KEY DEFAULT nextval('APPLICATION_SEQ'),
    name VARCHAR(255) NOT NULL UNIQUE,
    owner_team VARCHAR(255) NOT NULL,
    repo_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS RELEASE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS RELEASE (
    id INTEGER PRIMARY KEY DEFAULT nextval('RELEASE_SEQ'),
    application_id INTEGER NOT NULL,
    version VARCHAR(50) NOT NULL,
    env VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    evidence_url VARCHAR(255),
    version_row INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deployed_at TIMESTAMP,
    FOREIGN KEY (application_id) REFERENCES APPLICATION(id) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS APPROVAL_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS APPROVAL (
    id INTEGER PRIMARY KEY DEFAULT nextval('APPROVAL_SEQ'),
    release_id INTEGER NOT NULL,
    approver_email VARCHAR(255) NOT NULL,
    outcome VARCHAR(50) NOT NULL,
    notes TEXT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (release_id) REFERENCES RELEASE(id) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS AUDITLOG_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS AUDITLOG (
    id INTEGER PRIMARY KEY DEFAULT nextval('AUDITLOG_SEQ'),
    actor VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    entity VARCHAR(255) NOT NULL,
    entity_id INTEGER NOT NULL,
    payload JSONB,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);