name: Build dos artefatos de Frontend do projeto

on:
  workflow_call:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend-angular/package-lock.json

      - name: Install Dependencies
        working-directory: frontend-angular
        run: npm ci

      - name: Build Angular Application
        working-directory: frontend-angular
        run: npm run build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v6
        with:
          name: frontend-dist
          path: frontend-angular/dist/
          retention-days: 1